### ISSUE TITLE
How to change the speed of scrolling?

### ISSUE THREAD

**Issue by KirillGrigoriev** [tunnelvisionlabs/MouseFastScroll#13]
Are there any ways to change the speed of scrolling? This is very helpful extention, but too much lines per tick scrolling.

**Comment by sharwell** [comment]
There is currently no way to change it. The scrolling with <kbd>Ctrl</kbd> held down is controlled by the number of lines visible in the editor. It's equivalent to pressing <kbd>Page Down</kbd> except that it doesn't move the caret.
